/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_login (void);
GtkWidget* create_windowAddClient (void);
GtkWidget* create_windowEditClient (void);
GtkWidget* create_windowGesClient (void);
GtkWidget* create_windowDelClient (void);
GtkWidget* create_windowAnneSeche (void);
