/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_login (void)
{
  GtkWidget *window_login;
  GtkWidget *fixed1;
  GtkWidget *entry_userame;
  GtkWidget *entry_password;
  GtkWidget *label_hidden_6;
  GtkWidget *login;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label91;
  GtkWidget *creecompte;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label92;
  GtkWidget *label90;
  GtkWidget *label_password_6;
  GtkWidget *label_username_6;
  GtkWidget *label89;
  GtkWidget *image25;

  window_login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_login, 800, 500);
  gtk_window_set_title (GTK_WINDOW (window_login), _("Login"));
  gtk_window_set_position (GTK_WINDOW (window_login), GTK_WIN_POS_CENTER_ALWAYS);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_login), fixed1);

  entry_userame = gtk_entry_new ();
  gtk_widget_show (entry_userame);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_userame, 360, 160);
  gtk_widget_set_size_request (entry_userame, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_userame), 8226);

  entry_password = gtk_entry_new ();
  gtk_widget_show (entry_password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_password, 360, 232);
  gtk_widget_set_size_request (entry_password, 160, 30);
  gtk_entry_set_visibility (GTK_ENTRY (entry_password), FALSE);

  label_hidden_6 = gtk_cell_view_new ();
  gtk_widget_show (label_hidden_6);
  gtk_fixed_put (GTK_FIXED (fixed1), label_hidden_6, 160, 368);
  gtk_widget_set_size_request (label_hidden_6, 176, 32);

  login = gtk_button_new ();
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed1), login, 240, 312);
  gtk_widget_set_size_request (login, 150, 30);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (login), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Se Connecter"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox23), label91, FALSE, FALSE, 0);

  creecompte = gtk_button_new ();
  gtk_widget_show (creecompte);
  gtk_fixed_put (GTK_FIXED (fixed1), creecompte, 416, 312);
  gtk_widget_set_size_request (creecompte, 150, 30);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (creecompte), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Cr\303\251er un Compte"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox24), label92, FALSE, FALSE, 0);

  label90 = gtk_label_new (_("<span  foreground='#ff6600'  size='large' weight='bold'  style='oblique'>BORDJ LELLA</span>"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed1), label90, 296, 48);
  gtk_widget_set_size_request (label90, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label90), TRUE);
  gtk_label_set_justify (GTK_LABEL (label90), GTK_JUSTIFY_CENTER);

  label_password_6 = gtk_label_new (_("Password :"));
  gtk_widget_show (label_password_6);
  gtk_fixed_put (GTK_FIXED (fixed1), label_password_6, 216, 232);
  gtk_widget_set_size_request (label_password_6, 100, 30);

  label_username_6 = gtk_label_new (_("Username :"));
  gtk_widget_show (label_username_6);
  gtk_fixed_put (GTK_FIXED (fixed1), label_username_6, 216, 160);
  gtk_widget_set_size_request (label_username_6, 100, 30);

  label89 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed1), label89, 16, 8);
  gtk_widget_set_size_request (label89, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label89), TRUE);

  image25 = create_pixmap (window_login, "Sans titre..jpg");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed1), image25, 0, 0);
  gtk_widget_set_size_request (image25, 800, 500);
  gtk_widget_set_sensitive (image25, FALSE);

  g_signal_connect ((gpointer) login, "clicked",
                    G_CALLBACK (on_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) creecompte, "clicked",
                    G_CALLBACK (on_creecompte_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_login, window_login, "window_login");
  GLADE_HOOKUP_OBJECT (window_login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_login, entry_userame, "entry_userame");
  GLADE_HOOKUP_OBJECT (window_login, entry_password, "entry_password");
  GLADE_HOOKUP_OBJECT (window_login, label_hidden_6, "label_hidden_6");
  GLADE_HOOKUP_OBJECT (window_login, login, "login");
  GLADE_HOOKUP_OBJECT (window_login, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window_login, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window_login, image23, "image23");
  GLADE_HOOKUP_OBJECT (window_login, label91, "label91");
  GLADE_HOOKUP_OBJECT (window_login, creecompte, "creecompte");
  GLADE_HOOKUP_OBJECT (window_login, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window_login, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window_login, image24, "image24");
  GLADE_HOOKUP_OBJECT (window_login, label92, "label92");
  GLADE_HOOKUP_OBJECT (window_login, label90, "label90");
  GLADE_HOOKUP_OBJECT (window_login, label_password_6, "label_password_6");
  GLADE_HOOKUP_OBJECT (window_login, label_username_6, "label_username_6");
  GLADE_HOOKUP_OBJECT (window_login, label89, "label89");
  GLADE_HOOKUP_OBJECT (window_login, image25, "image25");

  return window_login;
}

GtkWidget*
create_windowAddClient (void)
{
  GtkWidget *windowAddClient;
  GtkWidget *fixed2;
  GtkWidget *entry_first_name_6;
  GtkWidget *entry_last_name_6;
  GtkWidget *entry_email_6;
  GtkWidget *entry_adress_6;
  GtkWidget *entry_phone_number_6;
  GtkWidget *entry_city_6;
  GtkObject *spinbutton_day_6_adj;
  GtkWidget *spinbutton_day_6;
  GtkObject *spinbutton_mouth_6_adj;
  GtkWidget *spinbutton_mouth_6;
  GtkObject *spinbutton_year_6_adj;
  GtkWidget *spinbutton_year_6;
  GtkWidget *entryid;
  GtkWidget *dateNclieAdd;
  GtkWidget *laleladress;
  GtkWidget *lalelnum;
  GtkWidget *lalelville;
  GtkWidget *button_add_client_confirm_6;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label15;
  GtkWidget *resultaddCl;
  GtkWidget *label_adress_6;
  GtkWidget *label_Last_name_6;
  GtkWidget *label_first_name_6;
  GtkWidget *button_add_client_back_6;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label88;
  GtkWidget *label_mounth;
  GtkWidget *label_year_6;
  GtkWidget *label_birth_date_6;
  GtkWidget *label_phone_number_6;
  GtkWidget *label_day;
  GtkWidget *label_city_6;
  GtkWidget *label87;
  GtkWidget *label_email_6;
  GtkWidget *lalelemail;
  GtkWidget *lalelnom;
  GtkWidget *lalelprenom;
  GtkWidget *idclientVerif;
  GtkWidget *label97;
  GtkWidget *comboboxentrysexe1;
  GtkWidget *label85;
  GtkWidget *label86;
  GtkWidget *image27;

  windowAddClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowAddClient, 790, 520);
  gtk_window_set_title (GTK_WINDOW (windowAddClient), _("Ajouter Client"));
  gtk_window_set_position (GTK_WINDOW (windowAddClient), GTK_WIN_POS_CENTER_ALWAYS);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowAddClient), fixed2);

  entry_first_name_6 = gtk_entry_new ();
  gtk_widget_show (entry_first_name_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_first_name_6, 208, 168);
  gtk_widget_set_size_request (entry_first_name_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_first_name_6), 8226);

  entry_last_name_6 = gtk_entry_new ();
  gtk_widget_show (entry_last_name_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_last_name_6, 560, 170);
  gtk_widget_set_size_request (entry_last_name_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_last_name_6), 8226);

  entry_email_6 = gtk_entry_new ();
  gtk_widget_show (entry_email_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_email_6, 200, 280);
  gtk_widget_set_size_request (entry_email_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_email_6), 8226);

  entry_adress_6 = gtk_entry_new ();
  gtk_widget_show (entry_adress_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_adress_6, 560, 280);
  gtk_widget_set_size_request (entry_adress_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_adress_6), 8226);

  entry_phone_number_6 = gtk_entry_new ();
  gtk_widget_show (entry_phone_number_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_phone_number_6, 200, 350);
  gtk_widget_set_size_request (entry_phone_number_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_phone_number_6), 8226);

  entry_city_6 = gtk_entry_new ();
  gtk_widget_show (entry_city_6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_city_6, 560, 352);
  gtk_widget_set_size_request (entry_city_6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_city_6), 8226);

  spinbutton_day_6_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_day_6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_day_6_adj), 1, 0);
  gtk_widget_show (spinbutton_day_6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_day_6, 380, 232);
  gtk_widget_set_size_request (spinbutton_day_6, 60, 25);

  spinbutton_mouth_6_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mouth_6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mouth_6_adj), 1, 0);
  gtk_widget_show (spinbutton_mouth_6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_mouth_6, 500, 232);
  gtk_widget_set_size_request (spinbutton_mouth_6, 60, 25);

  spinbutton_year_6_adj = gtk_adjustment_new (2020, 1950, 2030, 1, 10, 10);
  spinbutton_year_6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_year_6_adj), 1, 0);
  gtk_widget_show (spinbutton_year_6);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_year_6, 636, 232);
  gtk_widget_set_size_request (spinbutton_year_6, 60, 25);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed2), entryid, 376, 121);
  gtk_widget_set_size_request (entryid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  dateNclieAdd = gtk_label_new ("");
  gtk_widget_show (dateNclieAdd);
  gtk_fixed_put (GTK_FIXED (fixed2), dateNclieAdd, 712, 232);
  gtk_widget_set_size_request (dateNclieAdd, 30, 27);

  laleladress = gtk_label_new ("");
  gtk_widget_show (laleladress);
  gtk_fixed_put (GTK_FIXED (fixed2), laleladress, 720, 280);
  gtk_widget_set_size_request (laleladress, 30, 27);

  lalelnum = gtk_label_new ("");
  gtk_widget_show (lalelnum);
  gtk_fixed_put (GTK_FIXED (fixed2), lalelnum, 368, 350);
  gtk_widget_set_size_request (lalelnum, 30, 27);

  lalelville = gtk_label_new ("");
  gtk_widget_show (lalelville);
  gtk_fixed_put (GTK_FIXED (fixed2), lalelville, 720, 352);
  gtk_widget_set_size_request (lalelville, 32, 27);

  button_add_client_confirm_6 = gtk_button_new ();
  gtk_widget_show (button_add_client_confirm_6);
  gtk_fixed_put (GTK_FIXED (fixed2), button_add_client_confirm_6, 364, 416);
  gtk_widget_set_size_request (button_add_client_confirm_6, 120, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_add_client_confirm_6), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox2), label15, FALSE, FALSE, 0);

  resultaddCl = gtk_label_new (_("**********"));
  gtk_widget_show (resultaddCl);
  gtk_fixed_put (GTK_FIXED (fixed2), resultaddCl, 176, 456);
  gtk_widget_set_size_request (resultaddCl, 500, 30);

  label_adress_6 = gtk_label_new (_("Adresse :"));
  gtk_widget_show (label_adress_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_adress_6, 474, 280);
  gtk_widget_set_size_request (label_adress_6, 70, 27);

  label_Last_name_6 = gtk_label_new (_("Pr\303\251nom  :"));
  gtk_widget_show (label_Last_name_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_Last_name_6, 466, 170);
  gtk_widget_set_size_request (label_Last_name_6, 80, 27);

  label_first_name_6 = gtk_label_new (_("Nom  :"));
  gtk_widget_show (label_first_name_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_first_name_6, 136, 170);
  gtk_widget_set_size_request (label_first_name_6, 60, 27);

  button_add_client_back_6 = gtk_button_new ();
  gtk_widget_show (button_add_client_back_6);
  gtk_fixed_put (GTK_FIXED (fixed2), button_add_client_back_6, 32, 480);
  gtk_widget_set_size_request (button_add_client_back_6, 100, 30);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button_add_client_back_6), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox22), label88, FALSE, FALSE, 0);

  label_mounth = gtk_label_new (_("Mois :"));
  gtk_widget_show (label_mounth);
  gtk_fixed_put (GTK_FIXED (fixed2), label_mounth, 444, 230);
  gtk_widget_set_size_request (label_mounth, 55, 30);

  label_year_6 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label_year_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_year_6, 572, 230);
  gtk_widget_set_size_request (label_year_6, 60, 30);

  label_birth_date_6 = gtk_label_new (_("Date de naissance  :"));
  gtk_widget_show (label_birth_date_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_birth_date_6, 176, 230);
  gtk_widget_set_size_request (label_birth_date_6, 150, 27);

  label_phone_number_6 = gtk_label_new (_("Num\303\251ro t\303\251l\303\251phone :"));
  gtk_widget_show (label_phone_number_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_phone_number_6, 48, 352);
  gtk_widget_set_size_request (label_phone_number_6, 150, 27);

  label_day = gtk_label_new (_("Jour :"));
  gtk_widget_show (label_day);
  gtk_fixed_put (GTK_FIXED (fixed2), label_day, 316, 230);
  gtk_widget_set_size_request (label_day, 60, 30);

  label_city_6 = gtk_label_new (_("Ville  :"));
  gtk_widget_show (label_city_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_city_6, 488, 350);
  gtk_widget_set_size_request (label_city_6, 60, 27);

  label87 = gtk_label_new (_("ID :"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed2), label87, 328, 120);
  gtk_widget_set_size_request (label87, 50, 27);

  label_email_6 = gtk_label_new (_("Email :"));
  gtk_widget_show (label_email_6);
  gtk_fixed_put (GTK_FIXED (fixed2), label_email_6, 135, 280);
  gtk_widget_set_size_request (label_email_6, 60, 27);

  lalelemail = gtk_label_new ("");
  gtk_widget_show (lalelemail);
  gtk_fixed_put (GTK_FIXED (fixed2), lalelemail, 368, 280);
  gtk_widget_set_size_request (lalelemail, 30, 27);

  lalelnom = gtk_label_new ("");
  gtk_widget_show (lalelnom);
  gtk_fixed_put (GTK_FIXED (fixed2), lalelnom, 376, 168);
  gtk_widget_set_size_request (lalelnom, 30, 27);

  lalelprenom = gtk_label_new ("");
  gtk_widget_show (lalelprenom);
  gtk_fixed_put (GTK_FIXED (fixed2), lalelprenom, 728, 168);
  gtk_widget_set_size_request (lalelprenom, 30, 27);

  idclientVerif = gtk_label_new ("");
  gtk_widget_show (idclientVerif);
  gtk_fixed_put (GTK_FIXED (fixed2), idclientVerif, 537, 120);
  gtk_widget_set_size_request (idclientVerif, 29, 27);

  label97 = gtk_label_new (_("sexe :"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed2), label97, 144, 400);
  gtk_widget_set_size_request (label97, 57, 17);

  comboboxentrysexe1 = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxentrysexe1);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxentrysexe1, 200, 392);
  gtk_widget_set_size_request (comboboxentrysexe1, 112, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrysexe1), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrysexe1), _("Femme"));

  label85 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed2), label85, 16, 8);
  gtk_widget_set_size_request (label85, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label85), TRUE);

  label86 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Ajouter Client</span>"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed2), label86, 320, 40);
  gtk_widget_set_size_request (label86, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label86), TRUE);

  image27 = create_pixmap (windowAddClient, "Sans titre..jpg");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed2), image27, 0, 0);
  gtk_widget_set_size_request (image27, 792, 520);
  gtk_widget_set_sensitive (image27, FALSE);

  g_signal_connect ((gpointer) button_add_client_confirm_6, "clicked",
                    G_CALLBACK (on_button_add_client_confirm_6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_add_client_back_6, "clicked",
                    G_CALLBACK (on_button_add_client_back_6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAddClient, windowAddClient, "windowAddClient");
  GLADE_HOOKUP_OBJECT (windowAddClient, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_first_name_6, "entry_first_name_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_last_name_6, "entry_last_name_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_email_6, "entry_email_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_adress_6, "entry_adress_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_phone_number_6, "entry_phone_number_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entry_city_6, "entry_city_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, spinbutton_day_6, "spinbutton_day_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, spinbutton_mouth_6, "spinbutton_mouth_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, spinbutton_year_6, "spinbutton_year_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (windowAddClient, dateNclieAdd, "dateNclieAdd");
  GLADE_HOOKUP_OBJECT (windowAddClient, laleladress, "laleladress");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelnum, "lalelnum");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelville, "lalelville");
  GLADE_HOOKUP_OBJECT (windowAddClient, button_add_client_confirm_6, "button_add_client_confirm_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowAddClient, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowAddClient, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowAddClient, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowAddClient, resultaddCl, "resultaddCl");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_adress_6, "label_adress_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_Last_name_6, "label_Last_name_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_first_name_6, "label_first_name_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, button_add_client_back_6, "button_add_client_back_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (windowAddClient, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (windowAddClient, image22, "image22");
  GLADE_HOOKUP_OBJECT (windowAddClient, label88, "label88");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_mounth, "label_mounth");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_year_6, "label_year_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_birth_date_6, "label_birth_date_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_phone_number_6, "label_phone_number_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_day, "label_day");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_city_6, "label_city_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, label87, "label87");
  GLADE_HOOKUP_OBJECT (windowAddClient, label_email_6, "label_email_6");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelemail, "lalelemail");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelnom, "lalelnom");
  GLADE_HOOKUP_OBJECT (windowAddClient, lalelprenom, "lalelprenom");
  GLADE_HOOKUP_OBJECT (windowAddClient, idclientVerif, "idclientVerif");
  GLADE_HOOKUP_OBJECT (windowAddClient, label97, "label97");
  GLADE_HOOKUP_OBJECT (windowAddClient, comboboxentrysexe1, "comboboxentrysexe1");
  GLADE_HOOKUP_OBJECT (windowAddClient, label85, "label85");
  GLADE_HOOKUP_OBJECT (windowAddClient, label86, "label86");
  GLADE_HOOKUP_OBJECT (windowAddClient, image27, "image27");

  return windowAddClient;
}

GtkWidget*
create_windowEditClient (void)
{
  GtkWidget *windowEditClient;
  GtkWidget *fixed3;
  GtkWidget *entry_new_email;
  GtkWidget *entry_new_adress;
  GtkWidget *entry_new_city;
  GtkWidget *entry_new_number;
  GtkWidget *idclientEdit;
  GtkWidget *fisrtnameClEdit;
  GtkWidget *lastnameClEdit;
  GtkWidget *Adress;
  GtkWidget *label80;
  GtkWidget *label81;
  GtkWidget *label63;
  GtkWidget *label83;
  GtkWidget *City_;
  GtkWidget *button_back_edit_profile;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label84;
  GtkWidget *button_confirm_edit_profile;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label28;
  GtkWidget *resultEditCl;
  GtkWidget *Phonenumber;
  GtkWidget *ee;
  GtkWidget *aa;
  GtkWidget *lalelEMAIL;
  GtkWidget *lalelNOM;
  GtkWidget *lalelPRENOMM;
  GtkWidget *lalelADRESS;
  GtkWidget *lalelVILLE;
  GtkWidget *lalelNUM;
  GtkWidget *label98;
  GtkWidget *consultclient;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label64;
  GtkWidget *eventbox1;
  GtkWidget *comboboxentrysexe2;
  GtkWidget *image28;

  windowEditClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowEditClient, 800, 500);
  gtk_window_set_title (GTK_WINDOW (windowEditClient), _("Modifier Client"));
  gtk_window_set_position (GTK_WINDOW (windowEditClient), GTK_WIN_POS_CENTER_ALWAYS);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowEditClient), fixed3);

  entry_new_email = gtk_entry_new ();
  gtk_widget_show (entry_new_email);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_new_email, 168, 262);
  gtk_widget_set_size_request (entry_new_email, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_new_email), 8226);

  entry_new_adress = gtk_entry_new ();
  gtk_widget_show (entry_new_adress);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_new_adress, 520, 332);
  gtk_widget_set_size_request (entry_new_adress, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_new_adress), 8226);

  entry_new_city = gtk_entry_new ();
  gtk_widget_show (entry_new_city);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_new_city, 520, 262);
  gtk_widget_set_size_request (entry_new_city, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_new_city), 8226);

  entry_new_number = gtk_entry_new ();
  gtk_widget_show (entry_new_number);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_new_number, 168, 332);
  gtk_widget_set_size_request (entry_new_number, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_new_number), 8226);

  idclientEdit = gtk_entry_new ();
  gtk_widget_show (idclientEdit);
  gtk_fixed_put (GTK_FIXED (fixed3), idclientEdit, 312, 120);
  gtk_widget_set_size_request (idclientEdit, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idclientEdit), 8226);

  fisrtnameClEdit = gtk_entry_new ();
  gtk_widget_show (fisrtnameClEdit);
  gtk_fixed_put (GTK_FIXED (fixed3), fisrtnameClEdit, 168, 192);
  gtk_widget_set_size_request (fisrtnameClEdit, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (fisrtnameClEdit), 8226);

  lastnameClEdit = gtk_entry_new ();
  gtk_widget_show (lastnameClEdit);
  gtk_fixed_put (GTK_FIXED (fixed3), lastnameClEdit, 520, 192);
  gtk_widget_set_size_request (lastnameClEdit, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (lastnameClEdit), 8226);

  Adress = gtk_label_new (_("Adresse :"));
  gtk_widget_show (Adress);
  gtk_fixed_put (GTK_FIXED (fixed3), Adress, 435, 332);
  gtk_widget_set_size_request (Adress, 65, 30);

  label80 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed3), label80, 16, 8);
  gtk_widget_set_size_request (label80, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label80), TRUE);

  label81 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Modifier Client</span>"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed3), label81, 304, 40);
  gtk_widget_set_size_request (label81, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label81), TRUE);

  label63 = gtk_label_new (_("ID :"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed3), label63, 256, 120);
  gtk_widget_set_size_request (label63, 49, 27);

  label83 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed3), label83, 424, 192);
  gtk_widget_set_size_request (label83, 80, 27);

  City_ = gtk_label_new (_("Ville:"));
  gtk_widget_show (City_);
  gtk_fixed_put (GTK_FIXED (fixed3), City_, 448, 262);
  gtk_widget_set_size_request (City_, 60, 27);

  button_back_edit_profile = gtk_button_new ();
  gtk_widget_show (button_back_edit_profile);
  gtk_fixed_put (GTK_FIXED (fixed3), button_back_edit_profile, 24, 456);
  gtk_widget_set_size_request (button_back_edit_profile, 100, 30);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button_back_edit_profile), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label84 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox21), label84, FALSE, FALSE, 0);

  button_confirm_edit_profile = gtk_button_new ();
  gtk_widget_show (button_confirm_edit_profile);
  gtk_fixed_put (GTK_FIXED (fixed3), button_confirm_edit_profile, 368, 400);
  gtk_widget_set_size_request (button_confirm_edit_profile, 100, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_confirm_edit_profile), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox4), label28, FALSE, FALSE, 0);

  resultEditCl = gtk_label_new (_("**********"));
  gtk_widget_show (resultEditCl);
  gtk_fixed_put (GTK_FIXED (fixed3), resultEditCl, 168, 440);
  gtk_widget_set_size_request (resultEditCl, 500, 30);

  Phonenumber = gtk_label_new (_("Num\303\251ro t\303\251l\303\251phone :"));
  gtk_widget_show (Phonenumber);
  gtk_fixed_put (GTK_FIXED (fixed3), Phonenumber, 8, 332);
  gtk_widget_set_size_request (Phonenumber, 150, 27);

  ee = gtk_label_new (_("Email :"));
  gtk_widget_show (ee);
  gtk_fixed_put (GTK_FIXED (fixed3), ee, 96, 262);
  gtk_widget_set_size_request (ee, 60, 27);

  aa = gtk_label_new (_("Nom :"));
  gtk_widget_show (aa);
  gtk_fixed_put (GTK_FIXED (fixed3), aa, 96, 192);
  gtk_widget_set_size_request (aa, 60, 27);

  lalelEMAIL = gtk_label_new ("");
  gtk_widget_show (lalelEMAIL);
  gtk_fixed_put (GTK_FIXED (fixed3), lalelEMAIL, 336, 264);
  gtk_widget_set_size_request (lalelEMAIL, 30, 27);

  lalelNOM = gtk_label_new ("");
  gtk_widget_show (lalelNOM);
  gtk_fixed_put (GTK_FIXED (fixed3), lalelNOM, 336, 192);
  gtk_widget_set_size_request (lalelNOM, 30, 27);

  lalelPRENOMM = gtk_label_new ("");
  gtk_widget_show (lalelPRENOMM);
  gtk_fixed_put (GTK_FIXED (fixed3), lalelPRENOMM, 688, 192);
  gtk_widget_set_size_request (lalelPRENOMM, 30, 27);

  lalelADRESS = gtk_label_new ("");
  gtk_widget_show (lalelADRESS);
  gtk_fixed_put (GTK_FIXED (fixed3), lalelADRESS, 688, 336);
  gtk_widget_set_size_request (lalelADRESS, 30, 27);

  lalelVILLE = gtk_label_new ("");
  gtk_widget_show (lalelVILLE);
  gtk_fixed_put (GTK_FIXED (fixed3), lalelVILLE, 688, 264);
  gtk_widget_set_size_request (lalelVILLE, 30, 27);

  lalelNUM = gtk_label_new ("");
  gtk_widget_show (lalelNUM);
  gtk_fixed_put (GTK_FIXED (fixed3), lalelNUM, 336, 336);
  gtk_widget_set_size_request (lalelNUM, 30, 27);

  label98 = gtk_label_new (_("sexe :"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed3), label98, 96, 376);
  gtk_widget_set_size_request (label98, 56, 32);

  consultclient = gtk_button_new ();
  gtk_widget_show (consultclient);
  gtk_fixed_put (GTK_FIXED (fixed3), consultclient, 488, 120);
  gtk_widget_set_size_request (consultclient, 100, 27);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (consultclient), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox15), label64, FALSE, FALSE, 0);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox1, 168, 376);
  gtk_widget_set_size_request (eventbox1, 136, 31);

  comboboxentrysexe2 = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxentrysexe2);
  gtk_container_add (GTK_CONTAINER (eventbox1), comboboxentrysexe2);
  gtk_widget_set_size_request (comboboxentrysexe2, 136, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrysexe2), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrysexe2), _("Femme"));

  image28 = create_pixmap (windowEditClient, "Sans titre..jpg");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed3), image28, 0, 0);
  gtk_widget_set_size_request (image28, 808, 504);
  gtk_widget_set_sensitive (image28, FALSE);

  g_signal_connect ((gpointer) button_back_edit_profile, "clicked",
                    G_CALLBACK (on_button_back_edit_profile_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_confirm_edit_profile, "clicked",
                    G_CALLBACK (on_button_confirm_edit_profile_clicked),
                    NULL);
  g_signal_connect ((gpointer) consultclient, "clicked",
                    G_CALLBACK (on_consultclient_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowEditClient, windowEditClient, "windowEditClient");
  GLADE_HOOKUP_OBJECT (windowEditClient, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowEditClient, entry_new_email, "entry_new_email");
  GLADE_HOOKUP_OBJECT (windowEditClient, entry_new_adress, "entry_new_adress");
  GLADE_HOOKUP_OBJECT (windowEditClient, entry_new_city, "entry_new_city");
  GLADE_HOOKUP_OBJECT (windowEditClient, entry_new_number, "entry_new_number");
  GLADE_HOOKUP_OBJECT (windowEditClient, idclientEdit, "idclientEdit");
  GLADE_HOOKUP_OBJECT (windowEditClient, fisrtnameClEdit, "fisrtnameClEdit");
  GLADE_HOOKUP_OBJECT (windowEditClient, lastnameClEdit, "lastnameClEdit");
  GLADE_HOOKUP_OBJECT (windowEditClient, Adress, "Adress");
  GLADE_HOOKUP_OBJECT (windowEditClient, label80, "label80");
  GLADE_HOOKUP_OBJECT (windowEditClient, label81, "label81");
  GLADE_HOOKUP_OBJECT (windowEditClient, label63, "label63");
  GLADE_HOOKUP_OBJECT (windowEditClient, label83, "label83");
  GLADE_HOOKUP_OBJECT (windowEditClient, City_, "City_");
  GLADE_HOOKUP_OBJECT (windowEditClient, button_back_edit_profile, "button_back_edit_profile");
  GLADE_HOOKUP_OBJECT (windowEditClient, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (windowEditClient, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (windowEditClient, image21, "image21");
  GLADE_HOOKUP_OBJECT (windowEditClient, label84, "label84");
  GLADE_HOOKUP_OBJECT (windowEditClient, button_confirm_edit_profile, "button_confirm_edit_profile");
  GLADE_HOOKUP_OBJECT (windowEditClient, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowEditClient, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowEditClient, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowEditClient, label28, "label28");
  GLADE_HOOKUP_OBJECT (windowEditClient, resultEditCl, "resultEditCl");
  GLADE_HOOKUP_OBJECT (windowEditClient, Phonenumber, "Phonenumber");
  GLADE_HOOKUP_OBJECT (windowEditClient, ee, "ee");
  GLADE_HOOKUP_OBJECT (windowEditClient, aa, "aa");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelEMAIL, "lalelEMAIL");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelNOM, "lalelNOM");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelPRENOMM, "lalelPRENOMM");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelADRESS, "lalelADRESS");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelVILLE, "lalelVILLE");
  GLADE_HOOKUP_OBJECT (windowEditClient, lalelNUM, "lalelNUM");
  GLADE_HOOKUP_OBJECT (windowEditClient, label98, "label98");
  GLADE_HOOKUP_OBJECT (windowEditClient, consultclient, "consultclient");
  GLADE_HOOKUP_OBJECT (windowEditClient, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowEditClient, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowEditClient, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowEditClient, label64, "label64");
  GLADE_HOOKUP_OBJECT (windowEditClient, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (windowEditClient, comboboxentrysexe2, "comboboxentrysexe2");
  GLADE_HOOKUP_OBJECT (windowEditClient, image28, "image28");

  return windowEditClient;
}

GtkWidget*
create_windowGesClient (void)
{
  GtkWidget *windowGesClient;
  GtkWidget *fixed4;
  GtkWidget *label76;
  GtkWidget *addClient;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label79;
  GtkWidget *gotomodifier;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label59;
  GtkWidget *gotodelete;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label58;
  GtkWidget *homeGesClien;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label60;
  GtkWidget *buttonrefresh;
  GtkWidget *image26;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_admin_clients;
  GtkWidget *label77;
  GtkWidget *label94;
  GtkWidget *image29;

  windowGesClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowGesClient, 970, 570);
  gtk_window_set_title (GTK_WINDOW (windowGesClient), _("Gestion des clients"));
  gtk_window_set_position (GTK_WINDOW (windowGesClient), GTK_WIN_POS_CENTER_ALWAYS);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowGesClient), fixed4);
  gtk_widget_set_size_request (fixed4, 1000, 500);

  label76 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed4), label76, 16, 8);
  gtk_widget_set_size_request (label76, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label76), TRUE);

  addClient = gtk_button_new ();
  gtk_widget_show (addClient);
  gtk_fixed_put (GTK_FIXED (fixed4), addClient, 32, 144);
  gtk_widget_set_size_request (addClient, 100, 50);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (addClient), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox20), label79, FALSE, FALSE, 0);

  gotomodifier = gtk_button_new ();
  gtk_widget_show (gotomodifier);
  gtk_fixed_put (GTK_FIXED (fixed4), gotomodifier, 32, 214);
  gtk_widget_set_size_request (gotomodifier, 100, 50);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (gotomodifier), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Modifier "));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox11), label59, FALSE, FALSE, 0);

  gotodelete = gtk_button_new ();
  gtk_widget_show (gotodelete);
  gtk_fixed_put (GTK_FIXED (fixed4), gotodelete, 32, 284);
  gtk_widget_set_size_request (gotodelete, 100, 50);
  gtk_button_set_relief (GTK_BUTTON (gotodelete), GTK_RELIEF_HALF);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (gotodelete), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Supprimer "));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox10), label58, FALSE, FALSE, 0);

  homeGesClien = gtk_button_new ();
  gtk_widget_show (homeGesClien);
  gtk_fixed_put (GTK_FIXED (fixed4), homeGesClien, 824, 64);
  gtk_widget_set_size_request (homeGesClien, 100, 50);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (homeGesClien), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox12), label60, FALSE, FALSE, 0);

  buttonrefresh = gtk_button_new ();
  gtk_widget_show (buttonrefresh);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonrefresh, 490, 488);
  gtk_widget_set_size_request (buttonrefresh, 30, 30);

  image26 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_container_add (GTK_CONTAINER (buttonrefresh), image26);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 152, 128);
  gtk_widget_set_size_request (scrolledwindow1, 670, 352);

  treeview_admin_clients = gtk_tree_view_new ();
  gtk_widget_show (treeview_admin_clients);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_admin_clients);
  gtk_widget_set_size_request (treeview_admin_clients, 632, 312);
  GTK_WIDGET_SET_FLAGS (treeview_admin_clients, GTK_CAN_DEFAULT);

  label77 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Gestion des clients</span>"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed4), label77, 392, 32);
  gtk_widget_set_size_request (label77, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label77), TRUE);

  label94 = gtk_label_new (_("<span  foreground='#ff0000'  size='large' weight='bold'  style='roman'> *Double clique sur client  pour supprimer \n                  puis cliquer sur actualiser</span>"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed4), label94, 280, 520);
  gtk_widget_set_size_request (label94, 441, 48);
  gtk_label_set_use_markup (GTK_LABEL (label94), TRUE);

  image29 = create_pixmap (windowGesClient, "Sans titre..jpg");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed4), image29, 0, 0);
  gtk_widget_set_size_request (image29, 976, 576);
  gtk_widget_set_sensitive (image29, FALSE);

  g_signal_connect ((gpointer) addClient, "clicked",
                    G_CALLBACK (on_addClient_clicked),
                    NULL);
  g_signal_connect ((gpointer) gotomodifier, "clicked",
                    G_CALLBACK (on_gotomodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) gotodelete, "clicked",
                    G_CALLBACK (on_gotodelete_clicked),
                    NULL);
  g_signal_connect ((gpointer) homeGesClien, "clicked",
                    G_CALLBACK (on_buttonacceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrefresh, "clicked",
                    G_CALLBACK (on_buttonrefresh_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_admin_clients, "row_activated",
                    G_CALLBACK (on_treeview_admin_clients_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGesClient, windowGesClient, "windowGesClient");
  GLADE_HOOKUP_OBJECT (windowGesClient, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowGesClient, label76, "label76");
  GLADE_HOOKUP_OBJECT (windowGesClient, addClient, "addClient");
  GLADE_HOOKUP_OBJECT (windowGesClient, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (windowGesClient, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (windowGesClient, image20, "image20");
  GLADE_HOOKUP_OBJECT (windowGesClient, label79, "label79");
  GLADE_HOOKUP_OBJECT (windowGesClient, gotomodifier, "gotomodifier");
  GLADE_HOOKUP_OBJECT (windowGesClient, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowGesClient, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowGesClient, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowGesClient, label59, "label59");
  GLADE_HOOKUP_OBJECT (windowGesClient, gotodelete, "gotodelete");
  GLADE_HOOKUP_OBJECT (windowGesClient, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowGesClient, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowGesClient, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowGesClient, label58, "label58");
  GLADE_HOOKUP_OBJECT (windowGesClient, homeGesClien, "homeGesClien");
  GLADE_HOOKUP_OBJECT (windowGesClient, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowGesClient, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowGesClient, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowGesClient, label60, "label60");
  GLADE_HOOKUP_OBJECT (windowGesClient, buttonrefresh, "buttonrefresh");
  GLADE_HOOKUP_OBJECT (windowGesClient, image26, "image26");
  GLADE_HOOKUP_OBJECT (windowGesClient, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (windowGesClient, treeview_admin_clients, "treeview_admin_clients");
  GLADE_HOOKUP_OBJECT (windowGesClient, label77, "label77");
  GLADE_HOOKUP_OBJECT (windowGesClient, label94, "label94");
  GLADE_HOOKUP_OBJECT (windowGesClient, image29, "image29");

  gtk_widget_grab_focus (treeview_admin_clients);
  gtk_widget_grab_default (treeview_admin_clients);
  return windowGesClient;
}

GtkWidget*
create_windowDelClient (void)
{
  GtkWidget *windowDelClient;
  GtkWidget *fixed6;
  GtkWidget *entrysuppid;
  GtkWidget *labelsupprimerid;
  GtkWidget *buttonretourdelete;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label75;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *button_clients_delete;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label55;
  GtkWidget *outputDelClient;
  GtkWidget *image30;

  windowDelClient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowDelClient, 700, 450);
  gtk_window_set_title (GTK_WINDOW (windowDelClient), _("delete"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowDelClient), fixed6);
  gtk_widget_set_size_request (fixed6, 528, 440);

  entrysuppid = gtk_entry_new ();
  gtk_widget_show (entrysuppid);
  gtk_fixed_put (GTK_FIXED (fixed6), entrysuppid, 256, 184);
  gtk_widget_set_size_request (entrysuppid, 160, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysuppid), 8226);

  labelsupprimerid = gtk_label_new (_("ID :"));
  gtk_widget_show (labelsupprimerid);
  gtk_fixed_put (GTK_FIXED (fixed6), labelsupprimerid, 184, 184);
  gtk_widget_set_size_request (labelsupprimerid, 49, 30);

  buttonretourdelete = gtk_button_new ();
  gtk_widget_show (buttonretourdelete);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonretourdelete, 24, 376);
  gtk_widget_set_size_request (buttonretourdelete, 100, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonretourdelete), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox18), label75, FALSE, FALSE, 0);

  label72 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed6), label72, 16, 8);
  gtk_widget_set_size_request (label72, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label72), TRUE);

  label73 = gtk_label_new (_("<span  foreground='#7D1739'  size='large' weight='bold'  style='roman'> Supprimer Client</span>"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed6), label73, 280, 56);
  gtk_widget_set_size_request (label73, 248, 56);
  gtk_label_set_use_markup (GTK_LABEL (label73), TRUE);

  button_clients_delete = gtk_button_new ();
  gtk_widget_show (button_clients_delete);
  gtk_fixed_put (GTK_FIXED (fixed6), button_clients_delete, 440, 184);
  gtk_widget_set_size_request (button_clients_delete, 128, 30);
  gtk_container_set_border_width (GTK_CONTAINER (button_clients_delete), 1);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_clients_delete), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (image8), 1, 1);
  gtk_misc_set_padding (GTK_MISC (image8), 1, 1);

  label55 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox8), label55, FALSE, FALSE, 0);

  outputDelClient = gtk_label_new (_("***************"));
  gtk_widget_show (outputDelClient);
  gtk_fixed_put (GTK_FIXED (fixed6), outputDelClient, 200, 280);
  gtk_widget_set_size_request (outputDelClient, 400, 30);

  image30 = create_pixmap (windowDelClient, "Sans titre..jpg");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed6), image30, 0, 0);
  gtk_widget_set_size_request (image30, 704, 456);
  gtk_widget_set_sensitive (image30, FALSE);

  g_signal_connect ((gpointer) buttonretourdelete, "clicked",
                    G_CALLBACK (on_buttonretourdelete_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_clients_delete, "clicked",
                    G_CALLBACK (on_button_clients_delete_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowDelClient, windowDelClient, "windowDelClient");
  GLADE_HOOKUP_OBJECT (windowDelClient, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowDelClient, entrysuppid, "entrysuppid");
  GLADE_HOOKUP_OBJECT (windowDelClient, labelsupprimerid, "labelsupprimerid");
  GLADE_HOOKUP_OBJECT (windowDelClient, buttonretourdelete, "buttonretourdelete");
  GLADE_HOOKUP_OBJECT (windowDelClient, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (windowDelClient, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (windowDelClient, image18, "image18");
  GLADE_HOOKUP_OBJECT (windowDelClient, label75, "label75");
  GLADE_HOOKUP_OBJECT (windowDelClient, label72, "label72");
  GLADE_HOOKUP_OBJECT (windowDelClient, label73, "label73");
  GLADE_HOOKUP_OBJECT (windowDelClient, button_clients_delete, "button_clients_delete");
  GLADE_HOOKUP_OBJECT (windowDelClient, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowDelClient, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowDelClient, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowDelClient, label55, "label55");
  GLADE_HOOKUP_OBJECT (windowDelClient, outputDelClient, "outputDelClient");
  GLADE_HOOKUP_OBJECT (windowDelClient, image30, "image30");

  return windowDelClient;
}

GtkWidget*
create_windowAnneSeche (void)
{
  GtkWidget *windowAnneSeche;
  GtkWidget *fixed7;
  GtkWidget *label65;
  GtkWidget *entryansech1;
  GtkWidget *label95;
  GtkWidget *image31;
  GtkWidget *buttonAffAnSech1;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image32;
  GtkWidget *label96;

  windowAnneSeche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowAnneSeche, 616, 400);
  gtk_window_set_title (GTK_WINDOW (windowAnneSeche), _("Afficher l'ann\303\251e la plus s\303\251che"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (windowAnneSeche), fixed7);
  gtk_widget_set_size_request (fixed7, 616, 400);

  label65 = gtk_label_new (_("<span  foreground='#8CB4B8'  size='x-large' weight='bold'  style='roman'      >   SMART FARM        </span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed7), label65, 16, 8);
  gtk_widget_set_size_request (label65, 160, 46);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  entryansech1 = gtk_entry_new ();
  gtk_widget_show (entryansech1);
  gtk_fixed_put (GTK_FIXED (fixed7), entryansech1, 336, 152);
  gtk_widget_set_size_request (entryansech1, 200, 30);

  label95 = gtk_label_new (_("Lann\303\251e la plus s\303\251che:"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed7), label95, 176, 160);
  gtk_widget_set_size_request (label95, 153, 24);

  image31 = create_pixmap (windowAnneSeche, "Sans titre..jpg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed7), image31, 0, 0);
  gtk_widget_set_size_request (image31, 760, 512);
  gtk_widget_set_sensitive (image31, FALSE);

  buttonAffAnSech1 = gtk_button_new ();
  gtk_widget_show (buttonAffAnSech1);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonAffAnSech1, 336, 216);
  gtk_widget_set_size_request (buttonAffAnSech1, 144, 40);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (buttonAffAnSech1), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image32 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox25), image32, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("Afficher l'ann\303\251e"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox25), label96, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonAffAnSech1, "clicked",
                    G_CALLBACK (on_buttonAffAnSech1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAnneSeche, windowAnneSeche, "windowAnneSeche");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, label65, "label65");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, entryansech1, "entryansech1");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, label95, "label95");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, image31, "image31");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, buttonAffAnSech1, "buttonAffAnSech1");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, image32, "image32");
  GLADE_HOOKUP_OBJECT (windowAnneSeche, label96, "label96");

  return windowAnneSeche;
}

