/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_login;
  GtkWidget *windowAddClient;
  GtkWidget *windowEditClient;
  GtkWidget *windowGesClient;
  GtkWidget *windowDelClient;
  GtkWidget *windowEditPass;
  GtkWidget *windowAnneSeche;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_login = create_window_login ();
  gtk_widget_show (window_login);
  /*windowAddClient = create_windowAddClient ();
  gtk_widget_show (windowAddClient);
  windowEditClient = create_windowEditClient ();
  gtk_widget_show (windowEditClient);*/
  windowGesClient = create_windowGesClient ();
  gtk_widget_show (windowGesClient);
  //elli zedtou4
  GtkWidget *treeview911;
	
	
	treeview911 = lookup_widget(windowGesClient,"treeview_admin_clients");	
	afficher_clients(treeview911);
  /*windowDelClient = create_windowDelClient ();
  gtk_widget_show (windowDelClient);
  windowEditPass = create_windowEditPass ();
  gtk_widget_show (windowEditPass);*/
  windowAnneSeche = create_windowAnneSeche ();
  gtk_widget_show (windowAnneSeche);

  gtk_main ();
  return 0;
}

