/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_WRwindow1 (void);
GtkWidget* create_WRwindow2 (void);
GtkWidget* create_WRwindow3 (void);
GtkWidget* create_WRwindow4 (void);
